class Config:
    DATA_SOURCE = "yahoo"
    TICKERS = ["AAPL", "MSFT", "AMZN", "GOOGL", "NFLX", "XOM", "CVX", "PFE", "UNH", "JNJ"]
    START_DATE = "2019-01-01"
    END_DATE = "2024-12-31"

    RISK_FACTOR = 0.5
    BUDGET = 3
    PENALTY = 10.0

    QAOA_P = 2
    QAOA_OPTIMIZER = "COBYLA"
    QAOA_MAXITER = 50

    REGIME_MODEL = "hmm"
    REGIME_STATES = 3
    REGIME_THRESHOLD = 0.7

    USE_CVaR = True
    CVaR_ALPHA = 0.95

    TRANSACTION_COST = 0.001
    REBALANCE_THRESHOLD = 0.05